# Plugin Management
- repo: Shougo/dein.vim
- repo: wsdjeg/dein-ui.vim

# Colors and Icons
- repo: nvim-tree/nvim-web-devicons

- repo: rafi/awesome-vim-colorschemes

- repo: navarasu/onedark.nvim

# Startup
- repo: mhinz/vim-startify
  hook_add: source $VIM_PATH/config/plugins/startify.vim

# Navigation
- repo: christoomey/vim-tmux-navigator
  if: "! (has('win32') || has('win64'))"

- repo: nvim-tree/nvim-tree.lua
  on_cmd:
    [
      NvimTreeToggle,
      NvimTreeFocus,
      NvimTreeFindFile,
      NvimTreeCollapse,
      NvimTreeFindFileToggle,
    ]
  hook_source: luafile $VIM_PATH/config/plugins/nvimTree.lua

- repo: nvim-lua/plenary.nvim

- repo: airblade/vim-rooter
  hook_add: |
    let g:rooter_patterns = ['.git', '.svn', 'package.json', '!node_modules']

- repo: "nvim-telescope/telescope-fzf-native.nvim"
  build: "make"

- repo: nvim-telescope/telescope.nvim
  depends: [telescope-fzf-native.nvim, fzf]
  hook_source: luafile $VIM_PATH/config/plugins/telescope.lua

- repo: ibhagwan/fzf-lua
  depends: fzf
  hook_source: luafile $VIM_PATH/config/plugins/fzf.lua

- repo: junegunn/fzf
  build: "./install --all"
  merged: 0

# Register and Movemenets
- repo: justinmk/vim-sneak
  on_map:
    "nx": ["S", "s"]
  hook_add: |
    let g:sneak#label = 1
    let g:sneak#use_ic_scs = 1
    let g:sneak#s_next = 1
    let g:sneak#prompt = '🔎 '

- repo: unblevable/quick-scope
  on_map:
    "nx": ["f", "F", "t", "T"]
  hook_add: |
    let g:qs_highlight_on_keys = ['f', 'F', 't', 'T']
    highlight QuickScopePrimary guifg='#00C7DF' gui=underline ctermfg=155 cterm=underline
    highlight QuickScopeSecondary guifg='#eF5F70' gui=underline ctermfg=81 cterm=underline
    let g:qs_max_chars=150

- repo: ojroques/vim-oscyank
  lazy: 1
  hook_add: |
    let g:oscyank_term = 'default'
    let g:oscyank_silent = v:true

- repo: christoomey/vim-system-copy
  depends: [vim-oscyank]
  on_source: [vim-oscyank]
  on_map:
    "nx": ["cp", "cP", "cv", "cV"]
  hook_add: |
    let g:system_copy_enable_osc52 = 1

# Interface
- repo: machakann/vim-highlightedyank
  on_event: TextYankPost
  hook_source: let g:highlightedyank_highlight_duration = 300

- repo: simeji/winresizer
  on_cmd: WinResizerStartResize

- repo: hotwatermorning/auto-git-diff
  on_ft: gitrebase

- repo: norcalli/nvim-colorizer.lua
  if: has('nvim-0.4')
  on_event: FileType
  hook_source: luafile $VIM_PATH/config/plugins/colorizer.lua

- repo: nvim-lualine/lualine.nvim
  hook_source: luafile $VIM_PATH/config/plugins/lualine.lua

# Autocompletion
- repo: preservim/nerdcommenter
  on_map:
    [
      "<Leader>cc",
      "<leader>cn",
      "<leader>c<space>",
      "<leader>cm",
      "<leader>ci",
      "<leader>cs",
      "<leader>cy",
      "<leader>c$",
      "<leader>cA",
      "<leader>ca",
      "<leader>cl",
      "<leader>cb",
      "<leader>cu",
    ]

- repo: honza/vim-snippets

# Language and Files
- repo: nvim-treesitter/nvim-treesitter
  hook_post_update: TSUpdate
  hook_source: luafile $VIM_PATH/config/plugins/treesitter.lua

- repo: tpope/vim-rails
  on_ft: ruby

## LSP Support
- repo: neovim/nvim-lspconfig
- repo: "williamboman/mason.nvim"
- repo: "williamboman/mason-lspconfig.nvim"

## Autocompletion
- repo: 'hrsh7th/nvim-cmp'
- repo: 'hrsh7th/cmp-buffer'
- repo: 'hrsh7th/cmp-path'
- repo: 'saadparwaiz1/cmp_luasnip'
- repo: 'hrsh7th/cmp-nvim-lsp'
- repo: 'hrsh7th/cmp-nvim-lua'

##  Snippets
- repo: 'L3MON4D3/LuaSnip'
- repo: 'rafamadriz/friendly-snippets'

## LSP Config
- repo: 'VonHeikemen/lsp-zero.nvim'
  hook_source: luafile $VIM_PATH/config/plugins/lsp-zero.lua

## LSP UI
- repo: glepnir/lspsaga.nvim
  rev: 'main'
  hook_source: luafile $VIM_PATH/config/plugins/lspsaga.lua

# Other Stuff
- repo: tpope/vim-fugitive

- repo: mhinz/vim-signify
  hook_add: |
    let g:signify_sign_show_count = 0
    let g:signify_sign_show_text = 1

- repo: tpope/vim-surround

- repo: tpope/vim-repeat

# Search Replace
- repo: windwp/nvim-spectre
  hook_source: source $VIM_PATH/config/plugins/spectre.vim
