# Plugin Management
- repo: Shougo/dein.vim
- repo: wsdjeg/dein-ui.vim

# Colors and Icons
- repo: ryanoasis/vim-devicons

- repo: kristijanhusak/defx-icons
  depends: vim-devicons

- repo: rafi/awesome-vim-colorschemes

# Startup
- repo: mhinz/vim-startify
  hook_add: source $VIM_PATH/config/plugins/startify.vim

# Navigation
- repo: christoomey/vim-tmux-navigator
  if: "! (has('win32') || has('win64'))"

- repo: Shougo/defx.nvim
  on_cmd: Defx
  hook_source: source $VIM_PATH/config/plugins/defx.vim

- repo: junegunn/fzf
  build: "./install --all"
  merged: 0

- repo: junegunn/fzf.vim
  merged: 0
  depends: fzf
  on_cmd: [ Files, Buffers, History, BLines, Colors, Rg, Rgrep, GFiles ]
  on_func: [ 'fzf#vim#with_preview', 'fzf#run', 'vista#finder#fzf#Run', 'fzf#vim#grep' ]
  hook_source: source $VIM_PATH/config/plugins/fzf.vim

- repo: antoinemadec/coc-fzf
  depends: [coc.nvim, fzf.vim]
  on_source: fzf.vim

# Register and Movemenets
- repo: justinmk/vim-sneak
  on_map: {
    'nx': [ 'S', 's' ]
  }
  hook_add: |
    let g:sneak#label = 1
    let g:sneak#use_ic_scs = 1
    let g:sneak#s_next = 1
    let g:sneak#prompt = '🔎 '

- repo: unblevable/quick-scope
  on_map: {
    'nx': [ 'f', 'F', 't', 'T' ]
  }
  hook_add: |
    let g:qs_highlight_on_keys = ['f', 'F', 't', 'T']
    highlight QuickScopePrimary guifg='#00C7DF' gui=underline ctermfg=155 cterm=underline
    highlight QuickScopeSecondary guifg='#eF5F70' gui=underline ctermfg=81 cterm=underline
    let g:qs_max_chars=150

- repo: christoomey/vim-system-copy
  on_map: {
    'nx': [ 'cp', 'cP', 'cv', 'cV' ],
  }

# Interface
- repo: kristijanhusak/defx-git
  depends: defx.nvim
  on_source: defx.nvim

- repo: machakann/vim-highlightedyank
  on_event: TextYankPost
  hook_source: let g:highlightedyank_highlight_duration = 300

- repo: simeji/winresizer
  on_cmd: WinResizerStartResize

- repo: hotwatermorning/auto-git-diff
  on_ft: gitrebase

- repo: norcalli/nvim-colorizer.lua
  if: has('nvim-0.4')
  on_event: FileType
  hook_source: luafile $VIM_PATH/config/plugins/colorizer.lua

- repo: dhillondeep/eleline.vim
  hook_add: |
    let g:eleline_powerline_fonts = 1


# Autocompletion
- repo: preservim/nerdcommenter
  on_map: [ '<Leader>cc', '<leader>cn', '<leader>c<space>', '<leader>cm', '<leader>ci', '<leader>cs',
            '<leader>cy', '<leader>c$', '<leader>cA', '<leader>ca', '<leader>cl', '<leader>cb', '<leader>cu' ]

- repo: SirVer/ultisnips
- repo: honza/vim-snippets

# Language and Files
- repo: sheerun/vim-polyglot

- repo: tpope/vim-rails
  on_ft: ruby

- repo: fatih/vim-go
  on_ft: [ go, gomod ]
  hook_add: |
    let g:go_def_mapping_enabled = 0
    let g:go_code_completion_enabled = 0
    let g:go_fmt_command = "goimports"
    let g:go_template_autocreate = 0
    let g:go_decls_mode = "fzf"
    let g:go_echo_command_info = 0

# LSP
- repo: neoclide/coc.nvim
  merged: 0
  rev: release
  hook_source: source $VIM_PATH/config/plugins/coc.vim

# Other Stuff
- repo: tpope/vim-fugitive

- repo: tyru/open-browser.vim
- repo: tyru/open-browser-github.vim
  depends: open-browser.vim

- repo: mhinz/vim-signify
  hook_add: |
    let g:signify_sign_show_count = 0
    let g:signify_sign_show_text = 1

- repo: tpope/vim-surround

- repo: tpope/vim-repeat
